name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: brew update
      run: brew update
    - name: SDL2
      run: brew install sdl2
    - name: SDL2 image
      run: brew install sdl2_image
    - name: SDL2 ttf
      run: brew install sdl2_ttf
    - name: SDL2 mixer
      run: brew install sdl2_mixer
    - name: make
      run: code-the-classics/space-invaders/macos/make

