name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./space-invaders/macos

    steps:
    - uses: actions/checkout@v2
    - name: brew update
      run: brew update
    - name: install dependencies
      run: | 
        brew install SDL2
        brew install SDL2_image
        brew install SDL2_ttf
        brew install SDL2_mixer
    - name: make
      run: make
    - name: copy resources
      run: |
        cp -vr ./data ./build
    - name: Upload macOS Binary
      uses: actions/upload-artifact@v2
      with:
          name: apple-silicon
          path: ./build
