name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./space-invaders/macos

    steps:
    - uses: actions/checkout@v2
    - name: brew update
      run: brew update
    
    - name: install dependencies
      run: | 
        brew install SDL2
        brew install SDL2_image
        brew install SDL2_ttf
        brew install SDL2_mixer
        
    - name: copy resources
      run: |
        cp -vr ./data ./build
    
    - name: compile
      run: |
        g++ -Wall -std=c++17 source/*.cpp -o ./build/game -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer
    
    - name: compress
      run: tar -cvf artifacts.tar ./build
      
    - name: see files
      run: ls -al
    
    - name: upload macOS binary
      uses: actions/upload-artifact@v3
      with:
        name: game
        path: artifacts.tar
