name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./space-invaders/macos

    steps:
    - uses: actions/checkout@v2
    - name: brew update
      run: brew update
    - name: SDL2
      run: brew install sdl2
    - name: SDL2 image
      run: brew install sdl2_image
    - name: SDL2 ttf
      run: brew install sdl2_ttf
    - name: SDL2 mixer
      run: brew install sdl2_mixer
    - name: make
      run: make
    - name: copy resources
      run: |
        cp -vr ./data ./build
    - name: Upload macOS Binary
      uses: actions/upload-artifact@v2
      with:
          name: apple-silicon
          path: ./build
